# Name of the action.
name: Artifact Releaser

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for certain file changes on the main branch
  push:
    branches: [ cicd-implementation-main ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    android-build:
        name: Android Build
        runs-on: ubuntu-latest
        steps:
          - name: Checkout to cicd branch
            uses: actions/checkout@v3
            with:
              ref: cicd-implementation-main
          - name: npm Version check
            run: npm -v
          - name: Install npm dependency
            run: npm install
          - name: check directory.
            run: ls -lwr
          - name: Setup Android SDK
            uses: android-actions/setup-android@v2
          